### ISSUE TITLE
DAB really buggy/ not working

### ISSUE THREAD

**Issue by rubenverhoef** [rubenverhoef/OAP-Config#59]
DAB is really buggy...

When starting a radio station it works but without enough strength?
after a  few seconds it will fail to get audio, also shutdowns the dabboard.

**Comment by linuxchris12** [comment]
The station scan function and the scanning settings are currently optimized to find as many stations as possible. It will therefore also find stations which might be too weak for continuous audio playing. One can change this to accept only strong stations, if needed. 

What troubles me is that you write that the board shuts down. That should never happen, even if a station no longer cannot be received. Can you specify what you mean by "shutdown"?

**Comment by rubenverhoef** [comment]
Here is the full story:
I have tested the DAB board with a antenna which you can stick to the window at my desk at home. So i can get all code ready before putting it into my car.
After that i have put the DAB Board into my car with a cheap Chinese antenna for DAB+, FM and GPS. But FM was not working at all (for my OEM radio) and DAB+ was working but not as good as it should be.
So i bought a new antenna, this one: [Link](https://www.mbcaraudio.nl/universele-radio-accessoires/15096-calearo-16v-dabdabamfmgps-antenne.html). FM and GPS are working fine but DAB is not. The first time i tested it it looks like it works good, but after a while when driving the signal gets lost. I could tune again to the station but it was not reliable enough to listen to.

I have to test this more in my car but i have tested a small thing. What i saw was the following behavior:
* tuned to channel -> gives me audio output
* when getting the status of the DAB board it gives somewhere around 33 RSSI
* after a while the audio stops.
* checking the status it gives a lot of FIC errors and after a short time of checking it says the dabboard is shutdown.

I need to test this more in my car to get a better problem description.

The station i want to listen to should have enough strength.

Note: At my desk it was working fine, also when detaching and reattach the antenna, it goes on and on. so maybe i have introduced a bug in my setup or it has something to do with my new antenna.

**Comment by linuxchris12** [comment]
Thanks for the explanation. Unfortunately, I don't have much experience with using the board while moving around in a car. In principle I think receiving signal while moving is more difficult for the chip tuner to follow to the small frequency variations and signal disturbances which arise. 

I made some tests with antennas myself (I tested 5-6 of them) with the result that most of them give a worse signal then just a plain copper wire of 30cm length. However, you need something mounted on your car so you have no choice. Do you use a proper, shielded cable to connect the antenna? Or is there any other electric equipment around in your car which might disturb the Si468x?

Finally: that the Si468x shuts down did never happen to me, even if the DAB signal completely dies. I will try to reproduce this and try in my own car as well.
